name: Japanizer
version: 0.0.1
main: github.iharuya.japanizer.Japanizer
description: A plugin to Japanize chat messages. For example, "konnnichiwa" will be "こんにちは (konnnichiwa)".
api-version: 1.20
loadbefore: [DiscordSRV]
